# Generated by Django 4.0.2 on 2022-02-27 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0004_alter_products_category_alter_products_desc_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_column='ord_date', default=datetime.date.today)),
                ('qty', models.IntegerField(db_column='qty')),
                ('status', models.CharField(db_column='status', max_length=30)),
                ('customer_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product_id', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='reseller.products')),
            ],
            options={
                'db_table': 'order_tb',
            },
        ),
    ]
