# Generated by Django 4.0.2 on 2022-02-24 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(db_column='c_name', max_length=30)),
                ('company_regid', models.CharField(db_column='reg_id', max_length=12)),
                ('cmp_addr', models.CharField(db_column='addr', max_length=70)),
                ('country', models.CharField(db_column='cntry', max_length=30)),
                ('cmp_phno', models.CharField(db_column='phno', max_length=12)),
                ('acc_holder', models.CharField(db_column='acc_hld', max_length=30)),
                ('acc_no', models.CharField(db_column='acc_no', max_length=30)),
                ('acc_ifsc', models.CharField(db_column='ifsc', max_length=30)),
                ('user_type', models.CharField(db_column='type', max_length=20)),
                ('email', models.CharField(db_column='email', max_length=30)),
                ('user_id', models.IntegerField(db_column='log_id')),
                ('request_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='inactive', max_length=20)),
            ],
            options={
                'db_table': 'reseller_tb',
            },
        ),
    ]
