# Generated by Django 4.0.2 on 2022-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellers',
            name='passwd',
            field=models.CharField(db_column='passwd', default='', max_length=30),
            preserve_default=False,
        ),
    ]
