# Generated by Django 4.0.2 on 2022-02-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_resellers_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('reg_product_id', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('weight_unit', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=12)),
                ('subcategory', models.CharField(max_length=12)),
                ('vendor', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.resellers')),
            ],
        ),
    ]
