# Generated by Django 4.0.2 on 2022-02-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(db_column='cat', max_length=12),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(db_column='desc'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, db_column='img', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(db_column='price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(db_column='qty'),
        ),
        migrations.AlterField(
            model_name='products',
            name='reg_product_id',
            field=models.CharField(db_column='p_id', max_length=12),
        ),
        migrations.AlterField(
            model_name='products',
            name='reseller',
            field=models.ForeignKey(db_column='reseller', on_delete=django.db.models.deletion.CASCADE, to='reseller.resellers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(db_column='status', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.CharField(db_column='sub_cat', max_length=12),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(db_column='title', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.CharField(db_column='vendor', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(db_column='wt'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight_unit',
            field=models.CharField(db_column='unit', max_length=12),
        ),
        migrations.AlterModelTable(
            name='products',
            table='product_tb',
        ),
    ]
